/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 7970304c68e84fc300f492d0e0f9a771)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		REWRITE_ORIGIN: string;
		REWRITE_PATHS: string[];
		REWRITE_DEPTH: number;
		PROXY_ORIGIN: string;
	}
}
interface Env extends Cloudflare.Env {}
