/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: c0acb31a6297b2a3f6ea893819c74192)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		SOURCE_ORIGIN: string;
		SOURCE_PATHS: string;
		SOURCE_LEVELS: number;
		GH_REPO: string;
		GH_BRANCH: string;
		PROXY_ORIGIN: string;
	}
}
interface Env extends Cloudflare.Env {}
