/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false --strict-vars false` (hash: 949d539f67d350cf5ab1c942b60ba683)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env {
		PROXY_ORIGIN: string;
		PROXY_PATHS: string;
		PROXY_LEVELS: number;
		GH_REPO: string;
		GH_BRANCH: string;
	}
}
interface Env extends Cloudflare.Env {}
